# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('DateofBirth', models.DateField(max_length=8)),
                ('Email', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
